
GET http://localhost:8989/api/task_groups/all HTTP/1.1
Accept: application/json
Content-Type: application/json
###
GET http://localhost:8989/api/task_groups HTTP/1.1
Accept: application/json
Content-Type: application/json
###
POST http://localhost:8989/api/task_groups HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "New Task Group",
    "description": "This is a new task group created via the REST API."
}
###
PUT http://localhost:8989/api/task_groups HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "description": "This is a new task group created via the REST API.",
  "id": "62867de5-ce26-454e-877e-d171b5b7f815",
  "name": "New Task Groupzzzz"
}
###
PATCH http://localhost:8989/api/task_groups/4cddfddc-49c7-4c4d-a34a-caf862d8e19c HTTP/1.1
Accept: application/json
Content-Type: application/json
###
PATCH http://localhost:8989/api/task_groups/4cddfddc-49c7-4c4d-a34a-caf862d8e19c/enable HTTP/1.1
Accept: application/json
Content-Type: application/json
###

GET http://localhost:8989/api/activities HTTP/1.1
Accept: application/json
Content-Type: application/json
###

# Example response item for GET /api/activities:
# {
#   "id": "2f153858-fb39-4ac8-95a2-f5ee8217f7f3",
#   "group": "Development",
#   "task": "Implement API",
#   "started": "2026-03-01T10:00:00",
#   "ended": "2026-03-01T10:25:30",
#   "elapsed_hms": "00:25:30",
#   "description": "Initial implementation"
# }

